# Dependencies
markdown:         kramdown
remote_theme: fongandrew/hydeout
highlighter:      rouge

# Setup
title:            'Youngil Kim'
tagline:          'Personal Website'
description:      'PhD Student @ <a href="https://uci.edu/" target="_blank">UC Irvine</a>'
url:              https://fongandrew.github.io
# baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.